language: python
sudo: false
python:
- '2.7'
- '3.4'
install:
- pip install --upgrade tox-travis -r requirements-build.txt -r requirements-test.txt
script:
- tox
deploy:
  provider: pypi
  user: iotile
  skip_upload_docs: true
  on:
    branch: master
    tags: true
  password:
    secure: moZzO6rj8W4bAxddSA7m8s1zgsO1SliH/2Pkxocght5SgZ9JCE6mxQBdkv8knEiL4QiQuIBqSqP7mLNKPrjOPc9uzRGMjIRuEZlpIphIFjExmZa0ERwvpEW4P5nIHD2H08MZ2bsayuej4MfDz3fbg5LfuHuEyWb1Fyfok/t3QxYHG1TkMFKJsDGrwFbbM0OF2YwxIkbjNILltFR6zY/SXbTG0I+8srz/BRAyj8gMjXgoLTWIXl3adPhYRtwdJ2eBpBa47hXSe2TsA+sMobHzEV4qcvYsx2svdTAjrlvYgo5UftcO0k9t4iFRYgSwM1YZkOpYtExmi9d/ek2oEiLp6bOL6vfM7i8kgQFdgfnR0W6dRlCqsdkEoo2U5mNueigIXKl/680vACX5DWxfTVbNv6sK7fzyEP05efHbk861m23PId3zdcuWK4xQJYH7zHXEYFr89Fix6tiuEn69YYkPOsnYyP4CatdC7vhHc7kiQxfgHpNNPxBvxVsLg4cxQ1kY5dyzwo/228yrZr8pr3dAktAYtLu9d1sohE3w+PBBNaGnDeGy63QLebr5U4H+CN4hzTVoVMA/tYJVEzUpa6DHkwfzQucbKfrN5yABjMUz7YW/Lc5hKbDPgAddztjFSMPg6VRxFbZ2p1W/shm7FP7QStFeRYd1umKxl90mI0Myc2I=
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: qhlI6ILuy40WHTkLoNipyfk9wyDUFUh4u1RiMuVUQi4K+kfU0U5xG08f0N2nSzbkevGMGRtBMRLnQaqqcIhR+xc0uH+1rlV8fXN/6RXKDWyhaBhNCvhqxRIzvI1E983NfW2YBIIOwQnRT2YFHE26og+9mp5OBhlY8E88c4rdfwR7hUHByLKC5213Zw8dZhdg1KfIWZ0P/7HVPeEXwuLCLmyr1sR2TVyM0MoIhvqLFPbDkbFqbWTfZWCkoUYvmxDEGgVb8yPdWSnaxBKgWshR3CAw9W1+YLL57qBL5jHO6DSeT1PxEpJasLhFtO3PoGRpZstFKffUyjGIO/650DlKQfv+sfmt6LARK3gbcK1dVFhJAM7vIDHEHSSEin6QtHsrNsWKmYslHwJReNy5x7hci8347Nvs7ap3hZyiwqPPT0vYKyKNAOC5Scd+7wVai06iE7NiM47LMXVQNcLSLTFCwF+BDda2fdsBHKOy3syKjSHnMrlywg1B9KVSldUa/cWmygFW/Dz2lrYv9PmgApdR26dEHuloEuZ2xID33xKIT5O5f2Cpbc3uF8YYJcCuhccCLX+3cfLlTjdcyy9Hp1cNEG3gpA0S/Nr1HElEDH/b4B7uESJJsC+cZE1qqtXBZNZMNsU5EKXc60aBn7ZgTQVbWu0YwOrZD5VBLKh80X4MhoQ=
