language: python
sudo: false
python:
- '2.7'
- '3.4'
install:
- pip install --upgrade tox-travis -r requirements-build.txt -r requirements-test.txt
script:
- tox
deploy:
  provider: pypi
  user: iotile
  on:
    branch: master
    tags: true
  password:
    secure: hMNNT5A7OgjYr0WkMv3SxUReNW8XDq/ePeqxVIrwtMmOCnUXKmavrOPxz0xRPiEsgOoIuMIXmm4ja/VxP/t9jiDt44uF7v0ttkQ+PzW0M998vpVdq6e7ufFciaAdFc1V6gDRd5aw5QqJyk6sWrIKMa99glnI5XOw8SnnEBkpepTygUhUFoX7Nqq8otJWWb83FCo+5FLu+N3j2BDTJwuFakEIVqihZ0EWJqiZcvXX5YqengQteKwOzoyDZEPLGiCSnnMMz/RtuuCZ98r3XQKWivo57xmXjUfrxLj/k+42lILeE+MMCDNafZXax7soBOSX8QqOkRFdJ7mxE8v5xW9MWZf88qukGmMhS1ZRkdJ8HJ31uQeMjf0Si9mH2CgmtGUGxw4b8JIBUlmOyQ86qXYCtrR9FtotchqFE/gO3M78ALIYTm5sZYQwXyoFK6feGiq5hqP7k7zHyanJPUM6hisIt223JTWy6kFzjQk8Z9ImMM2Sz1d7xAl1L1bn2dLLxzyiCrTalldmiKD7RvOO/eAE9doiizzJShfX0rKd3jKrdEkm2LpRxWonOjREINMdc42eaBb5OrqqqTTTimMLG+D8skz2PKUl4lzg8/1sWM7xonHNcw4ZDAN6frXEJ/JC4PMqx9mMtDS3xtkqsCCJwdwFd21tjkGRCQ/wKaTx+1KcpVg=
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: qhlI6ILuy40WHTkLoNipyfk9wyDUFUh4u1RiMuVUQi4K+kfU0U5xG08f0N2nSzbkevGMGRtBMRLnQaqqcIhR+xc0uH+1rlV8fXN/6RXKDWyhaBhNCvhqxRIzvI1E983NfW2YBIIOwQnRT2YFHE26og+9mp5OBhlY8E88c4rdfwR7hUHByLKC5213Zw8dZhdg1KfIWZ0P/7HVPeEXwuLCLmyr1sR2TVyM0MoIhvqLFPbDkbFqbWTfZWCkoUYvmxDEGgVb8yPdWSnaxBKgWshR3CAw9W1+YLL57qBL5jHO6DSeT1PxEpJasLhFtO3PoGRpZstFKffUyjGIO/650DlKQfv+sfmt6LARK3gbcK1dVFhJAM7vIDHEHSSEin6QtHsrNsWKmYslHwJReNy5x7hci8347Nvs7ap3hZyiwqPPT0vYKyKNAOC5Scd+7wVai06iE7NiM47LMXVQNcLSLTFCwF+BDda2fdsBHKOy3syKjSHnMrlywg1B9KVSldUa/cWmygFW/Dz2lrYv9PmgApdR26dEHuloEuZ2xID33xKIT5O5f2Cpbc3uF8YYJcCuhccCLX+3cfLlTjdcyy9Hp1cNEG3gpA0S/Nr1HElEDH/b4B7uESJJsC+cZE1qqtXBZNZMNsU5EKXc60aBn7ZgTQVbWu0YwOrZD5VBLKh80X4MhoQ=
